# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='promo_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
